
REVIVAL_RECIPE_DATABASE_USER: postgres

test:
  TEST_DB_DATABASE_PASSWORD: myPg1!

development:
  REVIVAL_RECIPE_DEVELOPMENT_DATABASE_USERNAME: postgres
  REVIVAL_RECIPE_DEVELOPMENT_DATABASE_PASSWORD: myPg1!

production:
  REVIVAL_RECIPE_PRODUCTION_DATABASE_USERNAME: postgres
  REVIVAL_RECIPE_PRODUCTION_DATABASE_PASSWORD: myPg1!